# Generated by Django 3.1.4 on 2020-12-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/images')),
                ('section', models.CharField(choices=[('ENTERTAINMENT', 'Entertainment'), ('FASHION', 'Fashion'), ('BUSINESS', 'Business'), ('WOMEN', 'Women'), ('NEWS', 'News'), ('FEATURES', 'Features'), ('HUMANITY', 'Humanity'), ('WILDLIFE', 'Wildlife'), ('CRIME', 'Crime'), ('POLITICS', 'Politics')], max_length=200)),
                ('slug', models.SlugField(max_length=500)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='post/videos')),
            ],
        ),
    ]
