# Generated by Django 3.1.4 on 2021-06-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210119_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='section',
            field=models.CharField(choices=[('ENTERTAINMENT', 'Entertainment'), ('ENVIRONMENT', 'Environment'), ('BUSINESS', 'Business'), ('WOMEN', 'Women'), ('SPORTS', 'Sports'), ('HUMANITY', 'Humanity'), ('RESEARCH', 'Research'), ('PERSONAL', 'Personal'), ('INTERVIEWS', 'Interviews'), ('POLITICS', 'Politics'), ('TECHNOLOGY', 'Technology'), ('HEALTH', 'Health'), ('FEATURES', 'Features'), ('CRIME', 'Crime'), ('ROMANCE', 'Romance'), ('NEWS', 'news'), ('SDGS', 'SDGs')], max_length=200),
        ),
    ]
